### ISSUE TITLE
Mapping high quality assemblies to rGFA

### ISSUE THREAD

**Issue by egoltsman** [lh3/minigraph#10]
Hello,
I was able to build a fairly large graph from 12 complete and polished assemblies of individuals of a certain grass species (~270 mb genomes).  I am now trying to map them back to the rGFA graph.  Running minigraph with all defaults, the resulting GAF file has shorter alignments and fewer long paths than I would expect, so I'm suspecting that the default parameters might not be appropriate here.    Would you be able to recommend a set of flags for a case like this? 

The ***reference graph*** is quite fragmented, and here's the breakdown of the segment sizes:
#46629 total values totaling 279430451.0000. <5992.632289 +/- 24558.585829>
#Most likely bin: [ 0 - 100 ] 8549 counts
#Median bin: [ 400 - 500 ] 1502 counts

In the **GAF file** only 10% of the alignments are multi-segment paths.  These paths add up to about half of the total genome size.  Here's the breakdown of the aligned block sizes in the milti-segment paths:
#2584 total values totaling 152743151.0000. <59111.126548 +/- 73694.925338>
#Range: [ 180 - 589673 ]
#Most likely bin: [ 2000 - 3000 ] 83 counts
#Median bin: [ 32000 - 33000 ] 23 counts

Perhaps this is expected, but I'm wondering what can be tweaked to help increase the block size, thus capturing more and longer paths.   I'd be happy to share the data with you if you're interested.

Regards

**Comment by lh3** [comment]
> Running minigraph with all defaults

To map assemblies, you can try
```sh
minigraph -xasm
```

**Comment by a-slide** [comment]
For the record, I have tried to align assemblies with the option mentioned by @lh3 and it works perfectly fine for me. Using `-x lr` instead led to premature termination without error message.

**Comment by egoltsman** [comment]
Dear Heng,
To follow up,  I am now exploring the paths produced by mapping the assemblies back onto the graph.  The paths are made up of "stable" blocks, e.g.,
>Ref:7558445-7559373>Bd1_1:7817217-7817433>Ref:7559572-7565656

Now, it would be very useful to visualize them in one the graph viz tools that support paths. But since a single path element can represent several merged graph segments, one would need to translate that path back to a traditional path of "unstable" segments.   So, if the first stable element above was generated from, say, three unstable segments, then I'd like to see the path as s1>s2>s3>s9999>s5.   Can you suggest a way to do this conversion?   
The gfatools page seems to imply that both representations are possible.  Is that not the case?

Thank you

**Comment by lh3** [comment]
Use option `--vc`.

**Comment by egoltsman** [comment]
That worked!  It looks like this option must come before any other flags, which took a few tries to figure out.
Thanks for all your help

**Comment by lh3** [comment]
Could you show a command line where --vc is not work? Thanks.

**Comment by egoltsman** [comment]
My mistake. I must have use a single dash.
