### ISSUE TITLE
Path/allele were could not be traced

### ISSUE THREAD

**Issue by mekkiboussaha** [lh3/minigraph#105]
Sorry to bother you with this issue, but I am kind of new in the field and there are things that I could not understand.
I constructed the graph using 2 samples. Then I run gfatools to call SVs and finally I run "minigraph --call" to find the path/allele.
in the output file for this last step, I observed something like this:
19	6215950	6216037	>s32400	>s32402	*:0:+:19:6011048:6011135
19	6232539	6232540	>s32402	>s32404	.
What does the "." in the last column of the second result means exactly?
Thank you very much for your help.
Best regards

**Comment by ASLeonard** [comment]
Hey Mekki,
The "." is effectively missing (same as VCF), there is a more detailed answer here #34.

**Comment by mekkiboussaha** [comment]
Hi Alex and thanks a lot for your clarification.

Regards

Mekki
---
Mekki BOUSSAHA, Computational Biologist, IRHC, HDR
INRAE - UMR1313 GABI
Equipe Génétique et Génomique Bovines
78350 Jouy-en-Josas - France
Tel. : +33 1 34 65 26 46
________________________________
De : Alex Leonard ***@***.***>
Envoyé : mardi 5 décembre 2023 15:18:58
À : lh3/minigraph
Cc : Mekki Boussaha; Author
Objet : Re: [lh3/minigraph] Path/allele were could not be traced (Issue #105)


Hey Mekki,
The "." is effectively missing (same as VCF), there is a more detailed answer here #34<https://github.com/lh3/minigraph/issues/34>.

**Comment by lh3** [comment]
Thank you, @ASLeonard
