### ISSUE TITLE
Base-level alignments with -c -- comparison to MC

### ISSUE THREAD

**Issue by adadiehl** [lh3/minigraph#106]
Really a question for clarification rather than an issue. Just need to know if minigraph output when using the -c option is comparable to minigraph-cactus output. If not, in what way(s) does it differ? Thank you in advance for clarifying!

**Comment by lh3** [comment]
No, minigraph does not generate a base-level graph. Option -c only does base-level alignment.

**Comment by adadiehl** [comment]
Thank you for clarifying!
