### ISSUE TITLE
multiple mapping

### ISSUE THREAD

**Issue by yjk-bertrand** [lh3/minigraph#107]
I am using a blunted assembly graph from short reads that contains several paralogs. I am aligning a long read to the graph that should partially match several paths on the graph. I have tried several combinations of mapping parameters, varying the sequence divergence, the number of secondary alignments and other attempts. Yet, minigraph always outputs a single mapping for the query. Is there a way to get every mapping, even the partial ones?

**Comment by lh3** [comment]
Minigraph may map a read to different loci with option `--secondary=yes`, but it can't map a read to different haplotypes at the same locus.
