### ISSUE TITLE
description of `gfatools view -l` file

### ISSUE THREAD

**Issue by zeeev** [lh3/minigraph#108]
Hi @lh3,

I've been able to extract sub-graphs using the `-l` and a comma-separated command-line list, but providing a file for `-l` doesn't seem to work. Can you document what the format needs to be?

Thanks!

**Comment by lh3** [comment]
`-l@file.txt`. One segment name per file. This is the same as KMC.

**Comment by zeeev** [comment]
Thanks works as expected.
