### ISSUE TITLE
Meaning of optional tag fields in GAF format

### ISSUE THREAD

**Issue by a-slide** [lh3/minigraph#11]
Hi @lh3 
Thank for developing and maintaining minigraph. I believe it has a lot of potential.

Would you be able to comment on the meaning of the optional tags found at the end of each line in the GAF format ?

For example:
```tp:A:P cm:i:541394 s1:i:3239312 s2:i:7646 dv:f:0.0159```

I could not find the answer in neither GAF nor PAF formats specification

Thanks

**Comment by lh3** [comment]
See the minimap2 manpage: https://lh3.github.io/minimap2/minimap2.html#10

**Comment by a-slide** [comment]
Thanks.

It might be worth mentioning it in the GAF format document
