### ISSUE TITLE
Graph construction methods 

### ISSUE THREAD

**Issue by tanakash1028** [lh3/minigraph#111]
Thank you for developing the great algorithm.
I have a question regarding the method of graph construction and visualization of minigraph.

According to Extended Data Fig. 3 of a Nature paper entitled "A draft human pangenome reference," the copy number polymorphisms of chromosomal segments are represented by bubbles. (attached screenshot)
<img width="1325" alt="screenshot2024-03-26 18 34 10" src="https://github.com/lh3/minigraph/assets/90839483/1f658777-1a7d-4024-a77d-f49853cd417f">

I am wondering whether the number of bubbles increases if there are three or more copy number variations of chromosomal segments.
If there were three segments (S2, S3, and "S4") on the attached figure, would we see an additional bubble on minigraph? I mean, would there be two bubble loops?
Or would the number of bubbles not increase, and the path will cycle two times through the one bubble?"

**Comment by lh3** [comment]
> I am wondering whether the number of bubbles increases if there are three or more copy number variations of chromosomal segments.

Yes if they are generally <100kb in length

**Comment by tanakash1028** [comment]
@lh3 
Thank you very much for your prompt reply.
