### ISSUE TITLE
An error occurred when the sample.gfa file was generated

### ISSUE THREAD

**Issue by jiangwenhao3001** [lh3/minigraph#116]
``When run the following command line
minigraph -xggs -t16 13C.fa MP.fa > MP.gfa
The following error occurs
[M::main::1.106*0.52] loaded the graph from "13C.fa"
 [M::mg_index::9.517*1.53] indexed the graph
 [M::mg_opt_update::10.051*1.50] occ_weight=20, occ_max1=154; 95 percentile: 2
 [M::ggen_map::11.535*1.39] loaded file "MP.fa"
 [W::worker_for] stable sequence "chr10" already present in the graph. This will lead to inconsi    stent rGFA.
 [W::worker_for] stable sequence "chr11" already present in the graph. This will lead to inconsi    stent rGFA.
 [W::worker_for] stable sequence "chr12" already present in the graph. This will lead to inconsi    stent rGFA.
 [M::ggen_map::75.104*8.40] mapped 12 sequence(s) to the graph
 [W] stable sequence 'chr10' associated with different ranks on segment 's9208': 0 != 1
 [W] stable sequence 'chr10' associated with different ranks on segment 's9209': 0 != 1
 [W] stable sequence 'chr10' associated with different ranks on segment 's9210': 0 != 1
 [W] stable sequence 'chr10' associated with different ranks on segment 's9211': 0 != 1
 
 How to resolve the above error

**Comment by lh3** [comment]
You need to give each sequence a distinct name.
