### ISSUE TITLE
minigraph -cxasm --call -t16 graph.gfa sample-asm.fa > sample.bed

### ISSUE THREAD

**Issue by jiangwenhao3001** [lh3/minigraph#117]
The format of the sample.ded file is as follows
chr00   7937794 7938008 >s1     >s3     >s2:214:+:chrM2:105523:105744
chr00   8030470 8030529 >s3     >s5     >s4:59:+:chrM2:31524:31594
chr001  7625    7747    >s6     >s8     >s7:122:+:chr01:9105:9227
chr001  20277   20277   >s8     >s9     *:0:+:chr01:21752:21766
I would like to ask about the meaning of the fourth and fifth columns and the meaning of the beginning of the last column *

**Comment by lh3** [comment]
That is the path in the bubble corresponding to the sample. `*` for a zero-length path, effectively a deletion.
