### ISSUE TITLE
Very short segments in assembly

### ISSUE THREAD

**Issue by a-slide** [lh3/minigraph#12]
Hi @lh3,

I assembled 12 individual genomes assemblies together to create a pan-genome graph reference with minigraph. The shorter contigs in these individual assemblies were around 1300b.

I found out that in the resulting graph I have a quite a few very short segments (1 to 100 bases).
Even when I collapsing the data at stable sequence level I still have a number of short stable sequence. I am not convinced that these very short segments mean anything, in particular when considering nanopore error rate in particular in homopolymers. I also tried to increase the length of minimal variants (-L 500) but it doesn't seem to solve my issue.
Here is a length distribution plot both at stable sequence and segment level.

![index](https://user-images.githubusercontent.com/5701192/81944657-f8fb5080-95f4-11ea-83a5-0fad1e321ab6.png)

Are there any parameters to prevent these very short segments/contig to be added to the graph ?
Would it be an issue to manually prune out the shorter segments + associated links ?

Thanks
Ad

**Comment by lh3** [comment]
> Are there any parameters to prevent these very short segments/contig to be added to the graph ?
No, unfortunately. The short segments are there because 1) SVs are often not clean and 2) STRs/VNTRs introduce ambiguity.

Why do you care about those short segments?

**Comment by a-slide** [comment]
I was just confused about what these short contig actually mean. I use the graph to align reads and I am a bit worry that this short segments complicate the picture more than needed.
I think I will just manually remove segments shorter than 10 bases and just discard the associated link lines.  
It might be interesting to add an option to remove short segments after graph building and resolve the broken links.

**Comment by lh3** [comment]
These short segments are caused by SVs involving small changes in flanking regions or small variants arising later around SVs. If you remove them, you will break the graph topology.

**Comment by a-slide** [comment]
Yes I am sure it reflects small variations from the data, but I would be hesitant to call anything shorter than 10 bases an SV from nanopore data. I also understand that the graph topology will be affected, which is why I suggested that there might be a way to resolve broken links once a segment is removed.
It might not be a big deal at the end of the day, but I suspect the graph ends up being complicated by these small and not always relevant variations. In my case I am not really interested in small variations, (otherwise I would have used Illumina seq) but rather by the larger variants that Nanopore seq is good at catching.

Sorry for being insistent, I really think this is a very nice tool with a lot of potential.

Thanks

**Comment by lh3** [comment]
A segment doesn't represent an SV. In a minigraph graph, a bubble contains an SV. You can use `gfatools bubble` to extract bubbles.

**Comment by a-slide** [comment]
Ok thanks
