### ISSUE TITLE
Feature Request - Reference Path

### ISSUE THREAD

**Issue by fbemm** [lh3/minigraph#2]
Dear Heng,

would it be possible to add the choosen reference as path to the final GFA? Makes it easier to use it with other tools e.g., vg.

Bests,
Felix

**Comment by lh3** [comment]
Minigraph works with [rGFA](https://github.com/lh3/gfatools/blob/master/doc/rGFA.md), where the reference path is encoded in tags. It may support path encoding in future, but that won't happen soon.
