### ISSUE TITLE
program Aborted

### ISSUE THREAD

**Issue by shiyi-pan** [lh3/minigraph#21]
Hi, I compile the minigraph correctly but when I run it as followling command:

$MINIGRAPH/minigraph -xggs -t4 SoyC01.genome.fasta SoyC02.genome.fasta SoyC03.genome.fasta > out.gfa

I met an error like that:

[M::main::21.395*0.12] loaded the graph from "SoyC01.genome.fasta"
[M::mg_index::57.748*0.81] indexed the graph
[M::mg_opt_update::59.430*0.81] occ_weight=20, occ_max1=250; 95 percentile: 3
[M::ggen_map::79.927*0.64] loaded file "SoyC02.genome.fasta"
[M::ggen_map::1479.413*3.75] mapped 59 sequence(s) to the graph
[M::mg_ggsimple::1484.693*3.74] inserted 1275 events, including 0 inversions
[M::mg_index::1519.076*3.68] indexed the graph
[M::mg_opt_update::1520.781*3.68] occ_weight=20, occ_max1=250; 95 percentile: 3
[M::ggen_map::1540.860*3.63] loaded file "SoyC03.genome.fasta"
[M::ggen_map::3275.153*3.73] mapped 41 sequence(s) to the graph
minigraph: ggsimple.c:77: mg_ggsimple: Assertion `rs >= 0 && re > rs && re < g->seg[lc->v>>1].len' failed.
/gss1/home/hjb20181119/.lsbatch/1606288350.865135.shell: line 8: 11876 Aborted                 (core dumped) $MINIGRAPH/minigraph -xggs -t4 SoyC01.genome.fasta SoyC02.genome.fasta SoyC03.genome.fas
ta > out.gfa

could you help me fix the problem?  Thank you very much . My genome size is about 1Gb.

**Comment by lh3** [comment]
When did you clone the repo? There was a bug a few days ago. You may try the current github HEAD or a tagged release from the release page.

**Comment by shiyi-pan** [comment]
Thank you very much. I tried the current version and it worked well. Thank you a lot.
