### ISSUE TITLE
Visualization and SV detection after graph genome construction

### ISSUE THREAD

**Issue by jialei0701** [lh3/minigraph#23]
Dear Prof. Li,
After the construction of graph genome with minigraph, have you developed software to visualize the graph genome? And whether it is possible to carry out subsequent analysis such as SV detection based on rGAF?
Thank you.

**Comment by lh3** [comment]
I usually use bandage for visualization. You can use
```sh
gfatools bubble in.gfa > out.bed
```
to get the structural variations encoded in the graph.

**Comment by jialei0701** [comment]
OK, thank you.

**Comment by biozhangzhou** [comment]
> I usually use bandage for visualization. You can use
> 
> ```shell
> gfatools bubble in.gfa > out.bed
> ```
> 
> to get the structural variations encoded in the graph.

Hello,Prof. Li. what the meaning of every column in the bubble out file ? How do you get all the SVs in  you Minigraph paper and annotate it ?

**Comment by lh3** [comment]
Columns are described here: ftp://ftp.dfci.harvard.edu/pub/hli/minigraph/HPP/

mgutils.js anno does annotation but it is not for endusers. You are recommended to implement your own annotation pipelines.

**Comment by biozhangzhou** [comment]
Thank you.
