### ISSUE TITLE
Should GAF have a similar concept to secondary alignment from SAM?

### ISSUE THREAD

**Issue by SHuang-Broad** [lh3/minigraph#28]
Hello Heng,

As I was experimenting with the GAF format, I run into the following two mappings from the same read (GIAB HG002 15kb + 20kb CCS reads from their FTP site, mapped to GRCh38-freeze1 rGFA from your FTP site)

```
m64011_190830_220126/157353505/ccs	20538	8032	20531	+	<chr1:73847000-73939836<chr1:73717356-73846749	222229	8102593530	12002	12508	60	tp:A:P	cm:i:2149	s1:i:11931	s2:i:646	dv:f:0.0022
m64011_190830_220126/157353505/ccs	20538	2	7857	-	chr11	135086622	103201000	103208858	73457861	60	tp:A:P	cm:i:1315	s1:i:7294	s2:i:0	dv:f:0.0037
```

Notice they are both `tp:A:P` (not a bug, is it?), so I am wondering should there be a concept in GAF that is similar to the secondary alignment in SAM (i.e. flag 256)? It's immediately clear what that would mean though.

Note: there's a 251-bp HET deletion at this site (chr1) from HG002 relative to GRCh38.

Thanks
Steve

**Comment by lh3** [comment]
This is chimeric alignment, not secondary alignment. The output is expected preferred.

**Comment by SHuang-Broad** [comment]
Right, reading more about the manual, secondaries are already supported. I apologize.

A related question is how should supplementary alignments be represented, as currently column 6 provides that already.
Looking at the example above, the first part of the query/read is mapped to GRCh38#chr11, while the second part is mapped to GRCh38#chr1, which would be a split alignment (one of them has its flag 2048 turn on).

So my guess is that this related to the two chaining algorithms.

**Comment by lh3** [comment]
This could be a chimeric read or caused by larger SVs. Hard to tell from a single read.

**Comment by SHuang-Broad** [comment]
Assuming it was a translocation, what were the considerations that resulted in two records, as opposed to having a record with column 6 that map to 3 segments (e.g. `>chr11:...<chr1:...<chr1:...`)? 
Was it due to the second round of chaining which takes into consideration the graph topology?

**Comment by lh3** [comment]
There is not a path on the graph joining chr11 and chr1.

**Comment by SHuang-Broad** [comment]
I see. Thanks!

**Comment by lh3** [comment]
Welcome!
