### ISSUE TITLE
Question - Different ranks

### ISSUE THREAD

**Issue by fbemm** [lh3/minigraph#3]
Dear Heng,

Could you comment one the following minigraph warnings:

`[W] stable sequence 'flattened_line_31558' associated with different ranks on segment 's298030': 15 != 22`

Does this indicate deletions?

`[W::mg_ggsimple] query interval flattened_line_61364:1069-1069 is not covered`

This just means that a target did not get any query alignment?

Bests,
Felix

**Comment by lh3** [comment]
This means there is probably a minor internal bug lurking around. I haven't seen this on my datasets for a while. What is the version are you using?

**Comment by fbemm** [comment]
I am running `0.4-r279-dirty`. Both warnings appear quite frequently. Is that anyhow related to the assembly fragmentation or sequence length of the queries?

**Comment by lh3** [comment]
> I am running 0.4-r279-dirty

That is recent enough.

> I can package a 2-genome dataset and share in privately in case you need it.

Thank you!

**Comment by fbemm** [comment]
I send you a link via OneDrive. Hope that worked.

**Comment by fbemm** [comment]
Sequence IDs have to be unique across all input files. Thx Heng checking so quickly!

**Comment by lh3** [comment]
The latest version will warn about duplicated sequence names.

I am tuning parameters. The current github HEAD may not be very stable.

**Comment by a-slide** [comment]
Hi @lh3 
I got a lot of these warnings as well (171339 to be precise) on a version 0.10-dirty-r361. 
Should I be worried ?

```
[W] stable sequence 'ctg1' associated with different ranks on segment 's396905': 1 != 2
[W] stable sequence 'ctg1' associated with different ranks on segment 's396906': 1 != 2
[W] stable sequence 'ctg1' associated with different ranks on segment 's396907': 1 != 2
```

**Comment by lh3** [comment]
This usually happens when the same name appears in different input files. You should rename sequences, for example by adding a prefix/suffix.

**Comment by a-slide** [comment]
Thanks for the quick reply.
You mean during graph generation, right ?
Will this cause any downstream issues during mapping if I don't rename the contigs ?

**Comment by lh3** [comment]
Depending on what you, but generally you should avoid duplicated sequence names.

**Comment by a-slide** [comment]
Thanks Heng
