### ISSUE TITLE
Establishing paths faithfully 

### ISSUE THREAD

**Issue by egoltsman** [lh3/minigraph#30]
Hi Heng,
Once the graph is constructed, one often needs to trace paths through it that correspond to the constituent samples.  The only apparent way to do this in minigraph  is to map the assemblies back onto the graph, which is what I've been doing.    The accuracy of this depends heavily on the alignment criteria and the overall divergence between the samples, and so I've been struggling to get a faithful set of paths without leaving big chunks of the sample "unwalked".   It seems like a more direct (and hopefully more accurate) way would be to encode the paths right at the time of the incremental graph generation, lifting them over to the next set of nodes as new samples are added.  This is, of course, assuming that the mapping/chaining information is stores somewhere internally for each iteration.   I'm sure you've considered this, and I'd love to hear your thoughts on whether this is a good/doable idea.

**Comment by lh3** [comment]
> I've been struggling to get a faithful set of paths without leaving big chunks of the sample "unwalked"

See also #10. Most unwalked regions are too large/complex and are not represented in the graph.

Could you elaborate on why you want to trace paths? If the purpose is to call structural variations, v0.14 has a new option `--call` to call allelic path in each "bubble". For example
```sh
minigraph -xasm --call -t8 graph.gfa contigs.fa > out.bed
```
The output looks like
```txt
chr1    611316  612360  >s108   >s119   <s258835:10:+:HG01109#2#h2tg000153l:39193:39239
chr1    612492  612502  >s119   >s122   >s120>s305381:113:+:HG01109#2#h2tg000153l:39341:39454
chr1    626534  626781  >s122   >s124   >s123:247:+:HG01109#2#h2tg000153l:53499:53807
chr1    629056  634930  >s124   >s126   *:0:+:HG01109#2#h2tg000153l:56056:56061
chr1    641040  648375  >s126   >s128   >s127:7335:+:HG01109#2#h2tg000153l:62162:69513
chr1    651077  651077  >s128   >s129   *:0:+:HG01109#2#h2tg000153l:72205:72212
chr1    656639  656769  >s129   >s131   >s130:130:+:HG01109#2#h2tg000153l:77764:77900
```
Each line corresponds to a "bubble" in the graph. It indicates the path in the graph, the path length, the approximate contig region mapped to the path.

**Comment by lh3** [comment]
> lifting them over to the next set of nodes as new samples are added

Minigraph does approximate mapping. If we frequently replace existing segments, we will break the stability. In particular, we would like to keep the original reference sequence. If we do lift over, we will lose that.

**Comment by egoltsman** [comment]
Thanks for clarifying.  I can get the bubble calls now, but it seems like I still need something indicating whether the path matches the reference.  For example, here are two bubbles, with sample Bd1_1_CHR1 mapped onto them.  Only the second case is a variant wrt the reference while the first matches the reference path s18-s19-s20.   From the information provided I can only guess this from the non-consecutive node ids in the second case.  

Ref_CHR1        431463  431914  >s18    >s20    >s19:451:+:Bd1_1_CHR1:441352:441812
Ref_CHR1        508676  508765  >s20    >s22    >s10626:412:+:Bd1_1_CHR1:518512:518955

It would be great to see something like an allele call, say, 0 for reference and 1,2,etc for alternatives.   For complex bubbles (3 or more paths) this would be especially important to know.

Thanks!

**Comment by lh3** [comment]
I may add a reference field at some point. You can trace the segment ID for now.

> It would be great to see something like an allele call, say, 0 for reference and 1,2,etc for alternatives. For complex bubbles (3 or more paths) this would be especially important to know.

This is not possible for single-sample calling. You have to assign allele numbers with post processing.
