### ISSUE TITLE
extract non-reference sequence from the var.bed 

### ISSUE THREAD

**Issue by baozg** [lh3/minigraph#33]
Hi, @lh3 

We already have constructed a graph from 46 plant genomes. Some complex subgraph from the `minigraph` really impressive, but it need careful inspection since the vast repeat content in the plant genome. 

So We want to focus on the infomation from the non-reference insertion sequence in the graph. Since we have the `var.bed` from the `gfatools bubble` and reference calls from the `minigraph -t 64 -xasm --call G46.gfa reference.fasta > ref.bed`,can I extract non-reference insestion sequence in the `gfa`? If it is practial, how can I find the insertion from the gfa? Non-reference can use the "SN:Z" to distinctied with the reference.

**Comment by lh3** [comment]
> it need careful inspection since the vast repeat content in the plant genome

A complex subgraph only indicates complexity. The topology may not be optimal. In case of VNTRs, it is even not obvious what subgraph could be optimal.

> extract non-reference sequence

In the `bubble` output, the last two column corresponds to the sequences of the shortest and longest alleles.

**Comment by baozg** [comment]
> In the bubble output, the last two column corresponds to the sequences of the shortest and longest alleles.
Thanks for reply. Are the reference alleles shortest?

**Comment by lh3** [comment]
No. Reference allele may not be one of them.
