### ISSUE TITLE
Interpretation of "." in --call output

### ISSUE THREAD

**Issue by ASLeonard** [lh3/minigraph#34]
Hello,
After calling `--call` on a sample, there are multiple lines with the `:` separated output as mentioned in the documentation. However, there are also occasionally lines where the output is for example
```
chr4	181668	181723	>s6	>s8	.
```
It looks like this is the "default" output unless `p->t` is set [here](https://github.com/lh3/minigraph/blob/891124568430cd4dbf1ae9c11c0783e0b488d54a/asm-call.c#L111), presumably when a some match is found. Is the correct interpretation then that a `.` means no segment of the called sample matches any part of that bubble or its surroundings, hence not called as a deletion (`*`)?

**Comment by lh3** [comment]
`.` means missing, similar to `.` in VCF. Missing is mostly caused by the lack of alignment and occasionally caused by two or more long alignments at the locus.
