### ISSUE TITLE
Graph generation (-xggs) seems to be skipping some homozygous events

### ISSUE THREAD

**Issue by ecyeh** [lh3/minigraph#4]
I have 2 sequences, namely A and B, from an assembly of a human sample. The 2 sequences are very similar, and both contain an insertion of ~2150 bps, with breakpoints being mapped to the same location on GRCh38. 

I tried to add these insertions to my reference genome graph by feeding the fasta file of the A and B to minigraph, expecting at least 1 of the 2 insertions will be added to the GFA output. However it was not the case:

$ minigraph -t8 -xggs ref.gfa.gz A_and_B.fasta > AB_ref.gfa.gz
[M::main::14.491*1.00] loaded the graph from "ref.gfa.gz"
[M::mg_index::71.894*1.48] indexed the graph
[M::mg_opt_update::76.359*1.45] occ_weight=20, occ_max1=138; 95 percentile: 2
[M::ggen_map::76.376*1.45] loaded file "A_and_B.fasta"
[M::ggen_map::76.422*1.45] **mapped 2 sequence**(s) to the graph
[M::mg_ggsimple::76.422*1.45] **inserted 0 events**
[M::main] Version: 0.5-r294-dirty
........

But the first insertion is successfully added if the A and B are separated into 2 query files:

$ minigraph -t8 -xggs ref.gfa.gz A.fasta B.fasta > A_then_B_ref.gfa.gz
[M::main::14.495*1.00] loaded the graph from "ref.gfa.gz"
[M::mg_index::72.652*1.47] indexed the graph
[M::mg_opt_update::77.153*1.45] occ_weight=20, occ_max1=138; 95 percentile: 2
[M::ggen_map::77.156*1.45] loaded file "A.fasta"
[M::ggen_map::77.197*1.45] mapped 1 sequence(s) to the graph
[M::mg_ggsimple::78.418*1.44] **inserted 1 events**
[M::mg_index::137.816*1.48] indexed the graph
[M::mg_opt_update::142.177*1.47] occ_weight=20, occ_max1=138; 95 percentile: 2
[M::ggen_map::142.181*1.47] loaded file "B.fasta"
[M::ggen_map::142.201*1.47] mapped 1 sequence(s) to the graph
[M::mg_ggsimple::142.201*1.47] **inserted 0 events**
[M::main] Version: 0.5-r294-dirty
........

Is it a behavior by design?

**Comment by lh3** [comment]
Minigraph assumes each input file represents one haplotype genome. It only considers events in regions covered once. When you put two sequences in one file, the insertion will be covered twice and thus ignored.

**Comment by ecyeh** [comment]
> Minigraph assumes each input file represents one haplotype genome. 
Thank you for your reply, it is very helpful.
