### ISSUE TITLE
Other tools to contruct GFA from genome assemblies

### ISSUE THREAD

**Issue by ms-gx** [lh3/minigraph#41]
Are there other tools which can generate genome graphs (GFA/rGFA format or other) _de novo_ from genome assemblies like minigraph does? I am not talking about tools which use read alignment or VCFs for construction of graph. I want to use genome assemblies and generate the graph from them.

For a comparative study.

**Comment by colindaven** [comment]
@ms-gx 
I think vg will do this for you.

**Comment by subwaystation** [comment]
One can polish the graph from `minigraph` using https://github.com/ComparativeGenomicsToolkit/cactus. 

A real alternative could be https://github.com/pangenome/pggb. It can generate a pangenome graph from the all versus all alignments of the _de novo_ genome assemblies which aims to mitigate reference bias.
