### ISSUE TITLE
A 1 mb bubble - fact or fiction?

### ISSUE THREAD

**Issue by egoltsman** [lh3/minigraph#42]
Hello Heng,
In the graph I made from two complete haplomes of a large plant genome (basically, two sets of chromosomes with a fairly high confidence in the assembly), I see a few very large "bubbles", one as large as 1mb on the longer segment and 30kb on the shorter.  According to the minigraph paper, it "only considers SVs of 100 bp–100 kb in length".    Does this mean that the 1mb divergence is likely an artifact or are there scenarios where the algorithm can detect collinearity over a gap this large?

Thanks!

**Comment by ASLeonard** [comment]
Following up on this, I found an example where there is a bubble where both paths are approximately 1.2 Mb (bottom left), as well as a bubble where both paths are 13.5 Mb (right). This long region appears both in the `--call` bed file as well as the gaf file. The bottom arm in the huge bubble is from a single assembly (2nd used in construction), while the top arm is from two assemblies (reference and 3rd assembly).

![image](https://user-images.githubusercontent.com/29678761/115422199-f6d64480-a1fc-11eb-8f42-d5c69e186563.png)

**Comment by lh3** [comment]
Missed the original question. No, this is not an artifact. The alignment allows up to 100kb indels, but downstream steps may join long poorly aligned regions.

**Comment by ASLeonard** [comment]
As a follow up , after swapping the order of the samples used in construction (ref sample_3 sample_2), the 13.5 Mb bubble disappears. As you suggested, this looks like a series of poorly aligned regions constantly jumping locations (within +/- 5mb) and orientations for sample_2, hence possibly why it was a huge bubble when mapped 2nd, but aligns in smaller chunks when mapped 3rd.

I tried increasing the parameters set by `-xasm` (`-g1m -r1m --max-gap-pre=50k --min-cov-blen=1m --min-cov-mapq=20 --max-lc-skip=100 --max-gc-skip=100`) to see if it would overcome the small, poor alignments. There were slightly fewer nodes/edges/links in the graph, but the 13 Mb bubble was unchanged.

Are there any parameters or heuristics to adjust to avoid
> downstream steps may join long poorly aligned regions

and instead recover the long stretches of consensus + many smaller bubbles seen when swapping the sample order.

**Comment by lh3** [comment]
You can apply `--gg-match-pen=5` or smaller (default value: 10) to reduce large bubbles. However, most of these bubbles will be sensitive to alignment parameters and input ordering and are probably not biological.
