### ISSUE TITLE
gfa not finishing (stops at fasta indexing?)

### ISSUE THREAD

**Issue by GenerGener** [lh3/minigraph#43]
Hi Heng,

I have some transcripts as FASTA that I'm trying to graph relative to their reference (unspliced).

When I put in ./minigraph -xggs ref.fa multifasta.fa > out.gfa, the output is just the indexed fasta.

I tried splitting the multifasta.fa into single fasta, and moving to directory. No luck.

Using minigraph version 0.15.

The sample files also don't work.

**Comment by lh3** [comment]
Transcripts are far too short for minigraph to work. It is not the right unfortunately.

**Comment by GenerGener** [comment]
Ah ok. Thanks!
