### ISSUE TITLE
Question on allele

### ISSUE THREAD

**Issue by RenzoTale88** [lh3/minigraph#44]
Hello,
I've generate a graph using minigraph, extracted the bubbles and then called the samples using the guidelines in the website.
I'd like to see which allele a genome carries in comparison with the graph.
Fow example, if I paste the results of `gfatools bubble` and `minigraph --call`, I get a line like this:
```
genome1.chr1      2659    2829    4       2       0       170     170     -1      -1      -1      s2184,s307773,s2185,s2186       gtcctagatatatttttactatttttatgatcattcttttttttaatttttaaaaaaattttaaatcctctattactcctttaattttcattttttataacctatttattgctttgcaaaaaaaacccctattttttaaagcaaacttcatatatatatatatatatatg      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa      genome1.chr1      2659    2829    >s2184  >s2186  >s2185:170:+:genome1.chr1:2657:2830
```
I can see that genome1 carries the allele in path 2185. Is there a way to know which of the two alleles is 2185, or do I have to go back to the graph?

Thank you in advance
Andrea

**Comment by lh3** [comment]
You have to got back to the graph.
