### ISSUE TITLE
Coordinates of arbitrary sequence in graph

### ISSUE THREAD

**Issue by brunocontrerasmoreira** [lh3/minigraph#49]
Hi, I have built recently a graph of 10 genome assemblies with:

    minigraph -xggs -t 10 oryza_sativa_reference.fna fasta/*.fna -o oryza_sativa.gfa

Is there a way to find the coordinates of any arbitrary sequence from one of those assemblies in the graph without remapping it?
Thanks for your help,
Bruno

**Comment by lh3** [comment]
Unfortunately, minigraph doesn't keep track of sequence positions in the graph. You have to remap to find the coordinates. Sometimes, remapping may be inconsistent with graph generation. This is a problem I am thinking to improve in future.
