### ISSUE TITLE
Shasta input fasta

### ISSUE THREAD

**Issue by colindaven** [lh3/minigraph#51]
Hi all,

I'm interested in using FASTA sequences from the assembler Shasta in minigraph. These are ONT WGS human data.

I am having trouble with both haploid and (as expected) phased assembly input. Likely because they are overlapping.

This is the warning (many similar) with the haploid Shasta FASTA output (phased failed quicker, I guess this will fail later).

`[W::worker_for] stable sequence "BC.243" already present in the graph. This will lead to inconsistent rGFA.`

Has anyone used Shasta output for minigraph successfully, or shall I wind up some Flye assemblies ?

Thanks

Command line for rGFA build for 20 WGS FASTA

`minigraph -xggs -t $threads $ref $assemblies > $outgraph`

**Comment by lh3** [comment]
Input sequences should have different names. You need to rename your sequences.
