### ISSUE TITLE
Incorrect GAF path output if alignment spans 1 bp node

### ISSUE THREAD

**Issue by ASLeonard** [lh3/minigraph#52]
I've seen a few cases where a node of length 1 seems to result in incorrect gaf output. The gaf output indicates the path name is for example `>A:1000-2000` (all done using `--no-comp-path` flag), while in reality this segment is three nodes, of which the middle node is 1 bp long
```
A:1000-1499
A:1499-1500
A:1500-2000
```
And so the path the query is mapped to doesn't actually exist in the input gfa. Some real examples below from the gaf output

```
J00121:91:HHJHTBBXX:3:2205:13078:38363  302     8       296     +       >8_ARS:60641095-60653236        12141   7675    8232    272     557     60      tp:A:P  cm:i:42 s1:i:259        s2:i:0  dv:f:0.0073     ql:B:i,151,151
```

and the relevant gfa (noseq)
```
S       8_1816  *       LN:i:7918       SN:Z:8_ARS      SO:i:60641095   SR:i:0
S       8_1817  *       LN:i:1  SN:Z:8_ARS      SO:i:60649013   SR:i:0
S       8_1818  *       LN:i:4222       SN:Z:8_ARS      SO:i:60649014   SR:i:0
S       8_1819  *       LN:i:2160       SN:Z:8_ARS      SO:i:60653236   SR:i:0
```

Can see the path name spans multiple nodes, and the path "length" matches the sum of node lengths (12141 from gaf = 7918 + 1 + 4222).

**Comment by lh3** [comment]
> the path the query is mapped to doesn't actually exist in the input gfa

Why do you say so? The path is `>8_1816>8_1817>8_1818>8_1819` and in the stable coordinate, it is `>8_ARS:60641095-60653236`.

**Comment by ASLeonard** [comment]
I was expecting the path name to behave similar to with the `--vc` flag, which does output `>8_1816>8_1817>8_1818`, so in stable coordinates `>8_ARS:60641095-60649013>8_ARS:60649013-60649014>8_ARS:60649014-60653236`. I guess since the coordinate range is continuous, it makes more sense to represent that as `>8_ARS:60641095-60653236`.

**Comment by lh3** [comment]
> I guess since the coordinate range is continuous, it makes more sense to represent that as `>8_ARS:60641095-60653236`.

Yes, that is the reason.
