### ISSUE TITLE
minigraph call SV for Pacbio long reads but got empty .bed files

### ISSUE THREAD

**Issue by wzhang42** [lh3/minigraph#56]
Hi, Heng,
I use your prebuilt graph GRCh38-20-0.10b.gfa.gz(download from  ftp://ftp.dfci.harvard.edu/pub/hli/minigraph) to call SV. 
My command is as the following "minigraph -xasm --call GRCh38-20-0.10b.gfa.gz  sample-asm.fastq.gz  >sample.bed"  ,  I tried the "sample-asm.fastq.gz" with  Pacbio subread or CCS read from  (https://github.com/genome-in-a-bottle/giab_data_indexes), it  always report empty .bed files.   But I tried with GRCh38_no_alt.fa, and got something ( a .bed file with 30 more thousands lines) .   I am not sure whether minigraph only can call SV from genome scale assembly, but not for short read, even long read?      If so, what the smallest assemby length that can be supported, 50K, 1M, or longer?    Maybe my understanding is wrong. But I am very frustrated in the SV calling from Pacbio long read and always got 0 for the resulting .bed file.
 Thank you so much in advance.
Best
Wenchao

**Comment by lh3** [comment]
You call SV from contigs, not from reads.
