### ISSUE TITLE
Is there any solution or plan to use Minigraph to call SV from long read?  

### ISSUE THREAD

**Issue by wzhang42** [lh3/minigraph#57]
Hi, Heng, 
  I know vg can call SV from short reads. I am not sure whether there is any solution to use Minigraph to call SV from read or long reads.  If not, whether we have a plan to reach it.  Now, it seems like that only genome wide assembly or contig level assembly can be used to call SV. When I want to call SV from reads(short reads or long reads), I need  do the assembly of the reads before I can call SV, right?
     Best
Wenchao

**Comment by lh3** [comment]
Minigraph is unable to call SVs from reads.
