### ISSUE TITLE
Evaluate the Performance of sequence-to-graph mapping in minigraph and GraphAligner.

### ISSUE THREAD

**Issue by gsc74** [lh3/minigraph#60]
I want to evaluate the Performance of sequence-to-graph mapping as shown in `Table 2` in [minigraph](https://genomebiology.biomedcentral.com/track/pdf/10.1186/s13059-020-02168-z.pdf), for both `minigraph` and `GraphAligner`, I'm able to get numbers for minigraph with using `paftools.js mapeval minigraph_output.gaf`. [[paftools.js]](https://github.com/lh3/minimap2/tree/master/misc)
Output:
`Q	60	2778043	13768	0.004956007	       2778043 `
`Q	59	         828	         7	0.004957049	       2778871 `
`Q	58	         794	        6	0.004957792 	2779665`
`Q	57	         754	         6	0.004958605	2780419`
`Q	56	         838	         5	0.004958909	2781257`
`Q	55	         756	          4	0.004958999	2782013`
`........`
`........`
While using same command  `paftools.js mapeval GraphAligner_output.gaf`
Output :
`Q	60	2907330	2907330	1.000000000	2907330`
`Q	58	              1	             1	1.000000000	2907331`
`Q	56	            18	           18	1.000000000	2907349`
`............`
`.............`
@lh3  , I want to know what is the difference between `gaf` output of `minigraph` and `GraphAligner`, and why `paftools.js` is giving right numbers for `minigraph` while wrong numbers for `GraphAligner`.

**Comment by lh3** [comment]
You need to convert to the stable coordinate with `misc/mgutils.js stableGaf`

**Comment by lh3** [comment]
FYI: the master branch has just been updated with more accurate alignment.

**Comment by cjain7** [comment]
>FYI: the master branch has just been updated with more accurate alignment.

This is good news. Can we expect a stable release of minigraph in near future?

**Comment by lh3** [comment]
> Can we expect a stable release of minigraph in near future?

I hope to release the current github HEAD in this week. After the release, I will try to improve the performance of minigraph for species of higher diversity (see #62). In this case, full WFA is too slow. I need to implement heuristics in miniwfa and see how heuristics affect graphs.

> Can we expect new human rGFA graphs now?

For now, the most comprehensive human graph is the one I built for HPRC with v0.14. Here is the [zenodo link](https://zenodo.org/record/6286522). I will update the zenodo repo with graphs generated with the current github HEAD.

**Comment by cjain7** [comment]
Thank you!
