### ISSUE TITLE
Bacterial pangenome?

### ISSUE THREAD

**Issue by schorlton** [lh3/minigraph#67]
Hi @lh3, as per title - is minigraph suitable for generating bacterial pangenome graphs? All of the examples were eukaryotes that I just saw so just wondering how it will handle gene reassortment and large accessory genomes. Thanks!

**Comment by lh3** [comment]
Minigraph may work for strains at low divergence. I have tried it on Mtb strains. The graph looks ok-ish. I guess it would not work well for strains at high divergecen.

**Comment by schorlton** [comment]
Got it, thanks!!
