### ISSUE TITLE
Translocation not found by minigraph

### ISSUE THREAD

**Issue by VLoegler** [lh3/minigraph#68]
I am constructing a graph pan genome using several genome assemblies with Minigraph. One of my assembly contain a huge reciprocal translocation between 2 chromosomes: several hundreds of kb at the extremity of the 2 chromosomes are swapped. 

However, this translocation seems not to appear when visualising the graph with Bandage. The 2 chromosomes are not linked together. 

Is it expected ? Is there an option I could add to allow these kind of links ?

Thanks a lot

**Comment by lh3** [comment]
minigraph doesn't support translocations
