### ISSUE TITLE
Evaluation criteria for read mappings to rGFA.

### ISSUE THREAD

**Issue by gsc74** [lh3/minigraph#71]
@lh3, Assuming a case, where we are mapping a read to a rGFA with two mappers,
GAF output of the mappers (both output has mapping quality 60);
**mapper A (minigraph)**
``S1_3755!chr1!30892205!30902054!+	10000	97	9991	+	chr1	248956422	30892296	30902045	9226	10142	60	tp:A:P	NM:i:916	cm:i:371	s1:i:3736	s2:i:0	dv:f:0.0855``

**mapper B**
``S1_3755!chr1!30892205!30902054!+	10000	97	9991	+	>chr1:30771899-30894621>chr1:30894688-30972273	200307	120397	130079	9141	10163	60	tp:A:P	NM:i:1022	cm:i:189	s1:i:3159	s2:i:0	dv:f:0.1252``

When using `paftools.js mapeval` for evaluation of the correct mapping of a read, a read mapped by `mapper A` is considered a correct mapping. In contrast, a read mapped by `mapper B` is regarded as wrong mapping, even though `mapper B` has a 10% overlap with the reference coordinates.

Is it possible to include support in `paftools.js mapeval` to consider GAF output by `mapper B` as correct mapping?

**Comment by lh3** [comment]
> Is it possible to include support in paftools.js mapeval to consider GAF output by mapper B as correct mapping?

No. B is incorrect because it chooses a wrong path.

**Comment by gsc74** [comment]
Thank you!
