### ISSUE TITLE
problem to build a genome with minigraph

### ISSUE THREAD

**Issue by lingliao** [lh3/minigraph#84]
Hi Heng,

I tried to build a genome graph with command 
`minigraph -cxggs -t 16 cg_syn.fa ta_syn.fa > test.gfa`
The output file looks weird because there is no links at all. To make sure the input .fa files make sense, I intentionally generated two same .fa files and changed part of the sequences `range(int(0.4 * len(l)),int(0.7 * len(l)))`, so the output should have links as well.

I call minigraph with a docker image ` quay.io/biocontainers/minigraph:0.19--h7132678_1`, the command is `LSF_DOCKER_PRESERVE_ENVIRONMENT=false LSF_DOCKER_VOLUMES="/storage1/fs1/hprc/Active:/storage1/fs1/hprc/Active /scratch1/fs1/hprc:/scratch1/fs1/hprc" bsub -n 16 -G compute-hprc -Is -M 50GB -q general-interactive -R "select[mem>50000] rusage[mem=50000] span[hosts=1]" -a 'docker(quay.io/biocontainers/minigraph:0.19--h7132678_1)' /bin/bash`

The system pops that "We don't support that file type" when I tried to upload the input and output files, so, I sent them to your email account.

Thank you!

Ling

**Comment by lh3** [comment]
Minigraph has special use cases in mind. It is not intended for your simulated data. Please use real data.

**Comment by lingliao** [comment]
Hi Heng,

Thank you so much for trying to address the issue this late!!

With your suggestion, I then tried to build a graph with the test files provided in GitHub, MT.gfa and MT-orangA.fa.

Here is the command-
minigraph -cxggs -l10k MT.gfa MT-orangA.fa > A.gfa

The output file, A.gfa, is same as MT.gfa, now I am more confusion...

Thanks,

Ling

________________________________
