### ISSUE TITLE
unnecessary branches in rGFA ?

### ISSUE THREAD

**Issue by egoltsman** [lh3/minigraph#9]
Thank you for developing this tool - it looks very promising! 
I tried it on a three-genome set and got an rGFA file which I then converted to GFA2 and loaded into a visualize (I need the 'set' functionality of the graph to be able to be able to view different sample segments by color).   What I'm seeing quite often are reference segments with edges only to other reference segments, and the offsets suggesting that the two segments immediately follow each other.  If so, then what is the reason for splitting the stable reference segment at that position in the first place? 

Below is an extract from the graph where you can observe this.   Segments s8162 and s8163 are both from the Ref sample and are adjacent, according to the offset and lengh values.  The edge between them is not contested by any other edge.  I checked the original sequence, and there are not N's, gaps, or  repeats in this region.    Can you please explain?  

```
S	s8161	*	LN:i:82910	SN:Z:Ref	SO:i:26052560	SR:i:0
S	s8162	*	LN:i:578	SN:Z:Ref	SO:i:26135470	SR:i:0
S	s8163	*	LN:i:71969	SN:Z:Ref	SO:i:26136048	SR:i:0
S	s8164	*	LN:i:139743	SN:Z:Ref	SO:i:26208017	SR:i:0
S	s13329	*	LN:i:86	SN:Z:Bd21_3	SO:i:25992879	SR:i:1
S	s14767	*	LN:i:171	SN:Z:Bd25	SO:i:20514505	SR:i:2
L	s8161	+	s13329	+	0M	SR:i:1	L1:i:82910	L2:i:86
L	s8161	+	s8162	+	0M	SR:i:0	L1:i:82910	L2:i:578
L	s8162	+	s8163	+	0M	SR:i:0	L1:i:578	L2:i:71969
L	s8163	+	s8164	+	0M	SR:i:0	L1:i:71969	L2:i:139743
L	s8163	+	s14767	+	0M	SR:i:2	L1:i:71969	L2:i:171
```

The command I used was the one from the readme: minigraph -xggs  ref.fa  sample1.fa sample2.fa

Thank you

**Comment by lh3** [comment]
There should be other segments that create bifurcations; otherwise it is a bug.

**Comment by lh3** [comment]
PS: you can use `cat graph.gfa | grep 's8162\>'` to see all L-lines which are not necessarily clustered in the output GFA.

**Comment by lh3** [comment]
PSS: you can use `gfatools view -l s8162,s8163 -r2 graph.gfa` to extract a small graph around these two segments. It will be easier to investigate.

**Comment by egoltsman** [comment]
Sorry, I gave the wrong example.  Here's a good one from the same graph.  s8164 s8165 and s8166 are fragmented without any competing edges.  It looks like they should've been one vertex. 
```
gfatools view -S -l s8165,s8166 -r2 Bd21Ref.Bd21_3.Bd21-3_r.gfa
S	s8163	*	LN:i:71969	SN:Z:smpl-Ref.Bd4	SO:i:26136048	SR:i:0
S	s8164	*	LN:i:139743	SN:Z:smpl-Ref.Bd4	SO:i:26208017	SR:i:0
S	s8165	*	LN:i:3788	SN:Z:smpl-Ref.Bd4	SO:i:26347760	SR:i:0
S	s8166	*	LN:i:50439	SN:Z:smpl-Ref.Bd4	SO:i:26351548	SR:i:0
S	s14767	*	LN:i:171	SN:Z:smpl-Bd21_3_r.pseudomolecule_4	SO:i:20514505	SR:i:2
L	s8163	+	s8164	+	0M	SR:i:0	L1:i:71969	L2:i:139743
L	s8163	+	s14767	+	0M	SR:i:2	L1:i:71969	L2:i:171
L	s8164	+	s8166	+	0M	SR:i:2	L1:i:139743	L2:i:50439
L	s8164	+	s8165	+	0M	SR:i:0	L1:i:139743	L2:i:3788
L	s8165	+	s8166	+	0M	SR:i:0	L1:i:3788	L2:i:50439
L	s14767	+	s8164	+	0M	SR:i:2	L1:i:171	L2:i:139743
```

**Comment by lh3** [comment]
s8165 is deleted in SR:i:2. You can visualize in bandage.

**Comment by egoltsman** [comment]
Ah, I missed the different SR tags on the edges. My bad.  Using GfaViz here which doesn't allow tag-based edge coloring.  Thank you for clarifying this!

**Comment by lh3** [comment]
I only realized later that SR needs to be attached to edges as well. Also just to clarify: this 3.8kb s8165 deletion should be visible without the SR tag.

**Comment by egoltsman** [comment]
Right, but without the SR tag one can't tell in which sample the deletion happened. 
Thanks
